### ISSUE TITLE
package.json issues

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [vniche/rtk-query-grpc-web#1]
`"url": "git+https://gitub.com/vniche/rtk-query-grpc-web.git"`

Should be 
`"url": "https://github.com/vniche/rtk-query-grpc-web.git"`

Notice `no git+` needed and `github` instead of `gitub`

**Comment by vniche** [comment]
Thanks for noticing and taking the time to create the issue, [just solved](https://github.com/vniche/rtk-query-grpc-web/commit/67bc6db7bafb48019e75e3969d397f0f6cafc033).
